doctris/app/urls.py
from django.urls import path

from .all_views import core, admin, doctor, patient, landing

app_name = 'app'

urlpatterns = [

    
    #basic routes
    path('', core.index, name='index'),
    path('landing/', core.landing, name='landing'),
    path('signup/', landing.signup, name='signup'),
    path('login/', core.login_user, name='login'),
    path('logout/', core.logout_user, name='logout'),
    #core handler routes
    path('appointments/delete/<str:pk>', core.appointments_delete, name='appointmentdelete'),
    path('notification/toggle/<str:pk>', core.notification_toggle_seen, name='notiftoggle'),
    path('notification/delete/<str:pk>', core.notification_delete, name='notifdelete'),
    path('reminder/disable/', core.disable_reminder, name='disablereminder'),
    
    #admin home route
    path('admin/<str:tab>', admin.admin, name='admin'),
    #admin doctor routes
    path('admin/add/doctor', admin.admin_doc_form_add, name='adminadddoc'),
    path('admin/edit/doctor/<str:un>', admin.admin_doc_form_edit, name='admineditdoc'),
    path('admin/delete/doctor/<str:username>', admin.admin_doc_delete, name='admindeletedoc'),
    #admin parient routes
    path('admin/add/patient', admin.admin_pat_form_add, name='adminaddpat'),
    path('admin/edit/patient/<str:un>', admin.admin_pat_form_edit, name='admineditpat'),
    path('admin/delete/patient/<str:username>', admin.admin_pat_delete, name='admindeletepat'),
    #admin review appointments

    
    #doctor profile route
    path('doctor/', doctor.doctor, name='doctor'),
    #doctor appointment routes
    path('doctor/appointments', doctor.doctor_appointments_view, name='doctorappointments'),
    path('doctor/appointments/reminder', doctor.doctor_appointments_view_reminder, name='doctorappointmentsreminder'),
    path('doctor/notifications', doctor.doctor_notifications_view, name='doctornotif'),
    path('doctor/appointment/<str:pk>', doctor.doctor_appointment_edit, name='doctorappointmentsedit'),
    #doctor info route
    path('doctor/editinfo', doctor.doctor_edit_info, name='doctoreditinfo'),
    path('doctor/editcred', doctor.doctor_edit_cred, name='doctoreditcred'),
    #doctor actions route
    path('doctor/action/spec/<str:pk>', doctor.doctor_spec_relation, name='doctoractionspec'),
    path('doctor/action/aff/<str:pk>', doctor.doctor_aff_relation, name='doctoractionaff'),
    path('doctor/action/avail/<str:pk>', doctor.doctor_avail_relation, name='doctoractionavail'),
    path('doctor/delete/<str:rel_name>/<str:pk>', doctor.doctor_delete_relation, name='doctordeleterelation'),
    
    
    #patient profile route
    path('patient/', patient.patient, name='patient'),
    #patient home route
    path('patient/home', patient.patient_home, name='patienthome'),
    #patient notification route
    path('patient/notifications', patient.patient_notifications_view, name='patientnotif'),
    #patient info route
    path('patient/editinfo', patient.patient_edit_info, name='patienteditinfo'),
    path('patient/editcred', patient.patient_edit_cred, name='patienteditcred'),
    #patient  appointments route
    path('patient/appointments', patient.patient_appointments_view, name='patientappointments'),
    path('patient/appointment/<str:uname>/<str:pk>', patient.patient_doctor_appointment, name='patientdocappoint'),
    path('patient/appointments/reminder', patient.patient_appointments_view_reminder, name='patientappointmentsreminder'),
    path('patient/doctor/<str:uname>', patient.patient_doctor_view, name='patientdocview'),
    
    
]

doctris/hospitalAppointment/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('app.urls')),
    path('superuser/admin/', admin.site.urls),
]

doctris/app/templates/app/components/infoList/appointments.html
<div class="ui horizontal divider ms-5" >
    {% if as_doctor or as_custom %}
        {{title}}
    {% else %}
        Doctor's Appointments
    {% endif %}
</div>
<div class="ms-5 mt-5">
    {% for appoint in obj %}
        <div class="cust-list w-75 p-1" style="background-color: white; border-left: 2px solid #5174D5;">
            <div class="ms-3">
                <div class="profile-header">
                    {% if as_patient %}
                        Dr. {{ appoint.doctor.full_name }}
                    {% else %}
                        {% if as_admin %}
                            By {{ appoint.patient.full_name }} &nbsp; to &nbsp; Dr. {{ appoint.doctor.full_name }}
                        {% else %}
                            By {{ appoint.patient.full_name }}
                        {% endif %}
                    {% endif %}
                    {% if show_status %}
                        &nbsp;-&nbsp;{{ appoint.status.status }}
                    {% endif %}
                </div>
                <div class="profile-username">
                    {{ appoint.start_time }} to {{ appoint.end_time }}
                </div>
                <div class="profile-username">
                    {{ appoint.visit_date }}
                </div>
                {% if as_admin %}
                    <div class="profile-username">
                        payment Id: {{ appoint.payment.idx }}
                    </div>
                {% endif %}
                <br/>
            </div>
            <div class="cust-reveal">
                {% if has_edit %}
                    <a class="p-2 ui icon button" style="margin-right:13px" href="{% if has_patient_edit %}{% url 'app:patientdocappoint' appoint.doctor.username appoint.pk %}{% else %}{% url 'app:doctorappointmentsedit' appoint.pk %}{% endif %}" >
                        Edit
                    </a>
                {% endif %}
                <a class="p-2 ui icon button"  href="{% url 'app:appointmentdelete' appoint.pk %}"  >
                    Delete
                </a>
            </div>
        </div>
    {% endfor %}
</div>

doctris/app/templates/app/components/infoList/availiability.html
<div class="ui horizontal divider ms-5" >
    {% if as_doctor %}
        Your Working Hours
    {% else %}
        Doctor's Working Hours
    {% endif %}
</div>
<div class="ms-5" style="padding:14px;">
    {% for avail in avaliability %}
        <div class="cust-list">
            <div>
                <div class="profile-header">
                    {{ avail.day_in_week }}
                </div>
                <div class="profile-username">
                    @ {{ avail.starting_time }} - {{ avail.ending_time }}
                </div>
                <br/>
            </div>
            {% if as_doctor %}
                <div class="cust-reveal">
                    <a class="ui icon button" style="margin-right:13px" href="{% url "app:doctoractionavail" avail.pk %}" >
                        <i class="pencil alternate icon"></i>
                    </a>
                    <a class="ui icon button" href="{% url "app:doctordeleterelation" "avaliability" avail.pk %}" >
                        <i class="trash alternate icon"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    {% endfor %}
</div>

doctris/app/templates/app/components/infoList/hospital_affiliation.html
<div class="ui horizontal divider ms-5" >
    {% if as_doctor %}
        Your Hospital Affiliations
    {% else %}
        Doctor's Hospital Affiliations
    {% endif %}
</div>
<div class="ms-5" style="padding:14px;">
    {% for hosp in hospitals %}
        <div class="cust-list">
            <div>
                <div class="profile-header">
                    {{ hosp.hospital_name }}
                </div>
                <div class="profile-username">
                    @ {{ hosp.city }}, {{hosp.country}}
                </div>
                <br/>
            </div>
            {% if as_doctor %}
                <div class="cust-reveal">
                    <a class="ui icon button" style="margin-right:13px" href="{% url "app:doctoractionaff" hosp.pk %}"  >
                        <i class="pencil alternate icon"></i>
                    </a>
                    <a class="ui icon button" href="{% url "app:doctordeleterelation" "affiliations" hosp.pk %}" >
                        <i class="trash alternate icon"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    {% endfor %}
</div>

doctris/app/templates/app/components/infoList/specialties.html
<div class="ui horizontal divider ms-5" >
    {% if as_doctor %}
        Your Specialities
    {% else %}
        Doctor's Specialities
    {% endif %}
</div>
<div class="ms-5" style="padding:14px;">
    {% for spec in obj %}
        <div class="cust-list">
            <div>
                <div class="profile-header">
                    {{ spec.specialization_in }}
                </div>
                <div class="profile-username">
                    {{ spec.description }}
                </div>
                <br/>
            </div>
            {% if as_doctor %}
                <div class="cust-reveal">
                    <a class="ui icon button" style="margin-right:13px" href="{% url "app:doctoractionspec" spec.pk %}" >
                        <i class="pencil alternate icon"></i>
                    </a>
                    <a class="ui icon button"  href="{% url "app:doctordeleterelation" "speciality" spec.pk %}" >
                        <i class="trash alternate icon"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    {% endfor %}
</div>