doctris/app/urls.py
from django.urls import path

from .all_views import core, admin, doctor, patient, landing

app_name = 'app'

urlpatterns = [

    
    #basic routes
    path('', core.index, name='index'),
    path('landing/', core.landing, name='landing'),
    path('signup/', landing.signup, name='signup'),
    path('login/', core.login_user, name='login'),
    path('logout/', core.logout_user, name='logout'),
    #core handler routes
    path('appointments/delete/<str:pk>', core.appointments_delete, name='appointmentdelete'),
    path('notification/toggle/<str:pk>', core.notification_toggle_seen, name='notiftoggle'),
    path('notification/delete/<str:pk>', core.notification_delete, name='notifdelete'),
    path('reminder/disable/', core.disable_reminder, name='disablereminder'),
    
    #admin home route
    path('admin/<str:tab>', admin.admin, name='admin'),
    #admin doctor routes
    path('admin/add/doctor', admin.admin_doc_form_add, name='adminadddoc'),
    path('admin/edit/doctor/<str:un>', admin.admin_doc_form_edit, name='admineditdoc'),
    path('admin/delete/doctor/<str:username>', admin.admin_doc_delete, name='admindeletedoc'),
    #admin parient routes
    path('admin/add/patient', admin.admin_pat_form_add, name='adminaddpat'),
    path('admin/edit/patient/<str:un>', admin.admin_pat_form_edit, name='admineditpat'),
    path('admin/delete/patient/<str:username>', admin.admin_pat_delete, name='admindeletepat'),
    #admin review appointments

    
    #doctor profile route
    path('doctor/', doctor.doctor, name='doctor'),
    #doctor appointment routes
    path('doctor/appointments', doctor.doctor_appointments_view, name='doctorappointments'),
    path('doctor/appointments/reminder', doctor.doctor_appointments_view_reminder, name='doctorappointmentsreminder'),
    path('doctor/notifications', doctor.doctor_notifications_view, name='doctornotif'),
    path('doctor/appointment/<str:pk>', doctor.doctor_appointment_edit, name='doctorappointmentsedit'),
    #doctor info route
    path('doctor/editinfo', doctor.doctor_edit_info, name='doctoreditinfo'),
    path('doctor/editcred', doctor.doctor_edit_cred, name='doctoreditcred'),
    #doctor actions route
    path('doctor/action/spec/<str:pk>', doctor.doctor_spec_relation, name='doctoractionspec'),
    path('doctor/action/aff/<str:pk>', doctor.doctor_aff_relation, name='doctoractionaff'),
    path('doctor/action/avail/<str:pk>', doctor.doctor_avail_relation, name='doctoractionavail'),
    path('doctor/delete/<str:rel_name>/<str:pk>', doctor.doctor_delete_relation, name='doctordeleterelation'),
    
    
    #patient profile route
    path('patient/', patient.patient, name='patient'),
    #patient home route
    path('patient/home', patient.patient_home, name='patienthome'),
    #patient notification route
    path('patient/notifications', patient.patient_notifications_view, name='patientnotif'),
    #patient info route
    path('patient/editinfo', patient.patient_edit_info, name='patienteditinfo'),
    path('patient/editcred', patient.patient_edit_cred, name='patienteditcred'),
    #patient  appointments route
    path('patient/appointments', patient.patient_appointments_view, name='patientappointments'),
    path('patient/appointment/<str:uname>/<str:pk>', patient.patient_doctor_appointment, name='patientdocappoint'),
    path('patient/appointments/reminder', patient.patient_appointments_view_reminder, name='patientappointmentsreminder'),
    path('patient/doctor/<str:uname>', patient.patient_doctor_view, name='patientdocview'),
    
    
]

doctris/hospitalAppointment/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('app.urls')),
    path('superuser/admin/', admin.site.urls),
]

doctris/app/templates/app/components/appointment_form.html
{% if not success %}
    <div class="ui left aligned basic segment" >
        {% include './infoList/availiability.html' with obj=avaliability as_doctor=as_doctor title="Your Working Hours"%}
        {% include './infoList/appointments.html' with obj=appointments as_doctor=as_doctor title="Your Appointments"%}
        <div class="ui horizontal divider" >
            {% if as_edit %} 
                Edit Appointment  
            {% else %}
                Make Appointment 
            {% endif %}
        </div>
        <div style="padding:14px;">
            <form class="ui form admin-pat-form" action="" id="my-form" method="POST" autocomplete="off">
                {% csrf_token %} 
                <div class="field required">
                    <label>Visit Date</label>
                    <input type="date" id="visiting_date" {% if as_edit %} value="{{obj.visit_date}}" {% endif %} name="visit_date" min="{{today_date}}" required>
                </div>
                <div class="two fields">
                    <div class="field required">
                        <label>Start Time</label>
                        <input type="time" id="starting_time" {% if as_edit %} value="{{obj.start_time}}" {% endif %} name="start_time" min="00:00" max="24:00" required>
                    </div>
                    <div class="field required">
                        <label>End Time</label>
                        <input type="time" id="ending_time"  {% if as_edit %} value="{{obj.end_time}}" {% endif %}  name="end_time" min="00:00" max="24:00" required>
                    </div>
                </div>
                <div class="field">
                    <label>Appointment Notes</label>
                    {% if as_edit %}
                        <textarea rows="2" name="invite_reason"> {{obj.invite_reason}} </textarea>
                    {% endif %}
                    {% if not as_edit %}
                        <textarea rows="2" name="invite_reason">-</textarea>
                    {% endif %}
                </div>
                <div class="ui error message"></div>
                {% if invalid_time %}
                    <div class="ui negative message">
                        <p> Ending time was before Start time. <br/><br/>Please enter again. </p>
                    </div>
                {% endif %}
                {% if invalid_weekday %}
                    <div class="ui negative message">
                        <p> Dr. {{doctor.full_name}} is not avaliable that day of the week! 
                            <br/><br/>Please choose any other avaliable date.</p>
                    </div>
                {% endif %}
                {% if invalid_appointment_time %}
                    <div class="ui negative message">
                        <p> Dr. {{doctor.full_name}} is not avaliable that time of the day! <br/><br/>Please choose any other avaliable time.</p>
                    </div>
                {% endif %}
                {% if has_appointment_collision %}
                    <div class="ui negative message">
                        <p> Dr. {{doctor.full_name}} has another appointment that day! <br/><br/>Please choose any other avaliable time.</p>
                    </div>
                {% endif %}
                <div style="padding:14px;"></div>
                <div class="ui horizontal divider" >
                            {% if as_doctor or as_edit %}
                                <button class="ui teal button"type="submit" >
                                    Submit
                                </button>
                            {% else %}
                                <button class="ui teal button" type="submit" id="payment-button">
                                    Proceed to Payment
                                </button>
                            {% endif %}

                </div>
            </form>
        </div>
    </div>
{% if show_payment %}
    <script>
        var mobile = "{{patient.phone}}"
        var config = {
            "publicKey": "test_public_key_58b9d420775545388d85f7e97fde03bf",
            "productIdentity": "doctor_appointment",
            "productName": "Doctor_Appointment_Test",
            "productUrl": 'http://127.0.0.1:8000/patient/appointments',
            "eventHandler": {
                onSuccess (payload) {
                    console.log("payment successful");
                    console.log(JSON.stringify(payload));
                    var input = $("<input>")
                        .attr("type", "hidden")
                        .attr("name", "config").val(JSON.stringify(payload));
                    $('#my-form').append(input)
                    document.getElementById('my-form').submit();
                },
                onError (error) {
                    console.log("error with payment");
                    alert(error.payload.error_key);
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };
        var checkout = new KhaltiCheckout(config);
        checkout.show({amount: 1000, mobile});
    </script>
{% endif %}
{% else %}
    <div class="ui center aligned basic segment" style="margin-top: 60px;">
        <h1 class="ui icon header">
            <i class="check circle huge icon"></i>
            Success
        </h1>
        <div class="ui horizontal divider" style="margin-top: 60px;">
            &nbsp;
        </div>
        <div>
            <a class="ui teal  labeled icon button"type="submit" autofocus href="{% url "app:patientappointments" %}" >
                See Appointments
                <i class="eye icon" style="color:white"></i>
            </a>
            <a class="ui teal labeled icon button"type="submit" href="{% url "app:patienthome" %}"  >
                Make New
                <i class="add icon" style="color:white"></i>
            </a>
        </div>
    </div>
{% endif %}
    

doctris/app/templates/app/components/appointments.html
    {% include './infoList/appointments.html' with obj=todays_appointments has_edit=True as_custom=True title="Today's Appointments" has_patient_edit=has_patient_edit as_patient=as_patient %}

    {% include './infoList/appointments.html'  with obj=upcomming_appointments has_edit=True as_custom=True title="Upcomming Appointments" has_patient_edit=has_patient_edit as_patient=as_patient %}

    {% include './infoList/appointments.html'  with obj=past_appointments show_status=True has_edit=False as_custom=True title="Past Appointments" has_patient_edit=has_patient_edit as_patient=as_patient %}

doctris/app/templates/app/components/doctor_profile.html
<div class="ms-5 mt-5" style="padding:14px; position:relative">
    <div class="profile-header">
        Dr. {{ doctor.full_name }}
    </div>
    <div class="profile-username">
        @ {{ doctor.username }}
    </div>
    <br/>
    <div class="profile-default">
        email: &nbsp; {{ doctor.email }}
    </div>
    <div class="profile-default">
        phone: &nbsp; {{ doctor.phone }}
    </div>
</div>
{% include './infoList/availiability.html' with as_doctor=as_doctor obj=avaliability %}
{% include './infoList/specialties.html' with as_doctor=as_doctor obj=specializations %}
{% include './infoList/hospital_affiliation.html' with as_doctor=as_doctor obj=hospitals %}

doctris/app/templates/app/components/notifications.html
<div style="padding:7px;"></div>
    <div class="ui horizontal divider mt-5 ms-5" >
        New notifications
    </div>
    <div class="ms-5" style="padding:14px;">
        {% for notif in unseen %}
            <div class="cust-list">
                <div>
                    <div class="profile-header">
                        {{ notif.title }}
                    </div>
                    <div class="profile-username">
                        {{ notif.description }}
                    </div>
                    <br/>
                </div>
                <div class="cust-reveal">
                    <a class="ui icon button" style="margin-right:13px" href="{% url "app:notiftoggle" notif.pk %}" >
                        <i class="eye slash alternate icon"></i>
                    </a>
                    <a class="ui icon button"  href="{% url "app:notifdelete" notif.pk %}" >
                        <i class="trash alternate icon"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="ui horizontal divider ms-5" >
        Seen notifications
    </div>
    <div class="ms-5" style="padding:14px;">
        {% for notif in seen %}
            <div class="cust-list">
                <div>
                    <div class="profile-header">
                        {{ notif.title }}
                    </div>
                    <div class="profile-username">
                        {{ notif.description }}
                    </div>
                    <br/>
                </div>
                <div class="cust-reveal">
                    <a class="ui icon button" style="margin-right:13px" href="{% url "app:notiftoggle" notif.pk %}" >
                        <i class="eye alternate icon"></i>
                    </a>
                    <a class="ui icon button"  href="{% url "app:notifdelete" notif.pk %}" >
                        <i class="trash alternate icon"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>