doctris/app/urls.py
from django.urls import path

from .all_views import core, admin, doctor, patient, landing

app_name = 'app'

urlpatterns = [

    
    #basic routes
    path('', core.index, name='index'),
    path('landing/', core.landing, name='landing'),
    path('signup/', landing.signup, name='signup'),
    path('login/', core.login_user, name='login'),
    path('logout/', core.logout_user, name='logout'),
    #core handler routes
    path('appointments/delete/<str:pk>', core.appointments_delete, name='appointmentdelete'),
    path('notification/toggle/<str:pk>', core.notification_toggle_seen, name='notiftoggle'),
    path('notification/delete/<str:pk>', core.notification_delete, name='notifdelete'),
    path('reminder/disable/', core.disable_reminder, name='disablereminder'),
    
    #admin home route
    path('admin/<str:tab>', admin.admin, name='admin'),
    #admin doctor routes
    path('admin/add/doctor', admin.admin_doc_form_add, name='adminadddoc'),
    path('admin/edit/doctor/<str:un>', admin.admin_doc_form_edit, name='admineditdoc'),
    path('admin/delete/doctor/<str:username>', admin.admin_doc_delete, name='admindeletedoc'),
    #admin parient routes
    path('admin/add/patient', admin.admin_pat_form_add, name='adminaddpat'),
    path('admin/edit/patient/<str:un>', admin.admin_pat_form_edit, name='admineditpat'),
    path('admin/delete/patient/<str:username>', admin.admin_pat_delete, name='admindeletepat'),
    #admin review appointments

    
    #doctor profile route
    path('doctor/', doctor.doctor, name='doctor'),
    #doctor appointment routes
    path('doctor/appointments', doctor.doctor_appointments_view, name='doctorappointments'),
    path('doctor/appointments/reminder', doctor.doctor_appointments_view_reminder, name='doctorappointmentsreminder'),
    path('doctor/notifications', doctor.doctor_notifications_view, name='doctornotif'),
    path('doctor/appointment/<str:pk>', doctor.doctor_appointment_edit, name='doctorappointmentsedit'),
    #doctor info route
    path('doctor/editinfo', doctor.doctor_edit_info, name='doctoreditinfo'),
    path('doctor/editcred', doctor.doctor_edit_cred, name='doctoreditcred'),
    #doctor actions route
    path('doctor/action/spec/<str:pk>', doctor.doctor_spec_relation, name='doctoractionspec'),
    path('doctor/action/aff/<str:pk>', doctor.doctor_aff_relation, name='doctoractionaff'),
    path('doctor/action/avail/<str:pk>', doctor.doctor_avail_relation, name='doctoractionavail'),
    path('doctor/delete/<str:rel_name>/<str:pk>', doctor.doctor_delete_relation, name='doctordeleterelation'),
    
    
    #patient profile route
    path('patient/', patient.patient, name='patient'),
    #patient home route
    path('patient/home', patient.patient_home, name='patienthome'),
    #patient notification route
    path('patient/notifications', patient.patient_notifications_view, name='patientnotif'),
    #patient info route
    path('patient/editinfo', patient.patient_edit_info, name='patienteditinfo'),
    path('patient/editcred', patient.patient_edit_cred, name='patienteditcred'),
    #patient  appointments route
    path('patient/appointments', patient.patient_appointments_view, name='patientappointments'),
    path('patient/appointment/<str:uname>/<str:pk>', patient.patient_doctor_appointment, name='patientdocappoint'),
    path('patient/appointments/reminder', patient.patient_appointments_view_reminder, name='patientappointmentsreminder'),
    path('patient/doctor/<str:uname>', patient.patient_doctor_view, name='patientdocview'),
    
    
]

doctris/hospitalAppointment/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('app.urls')),
    path('superuser/admin/', admin.site.urls),
]

doctris/app/templates/app/admin_doc_tab.html
{% extends 'app/admin_page.html' %}

{% block home_click %}{% url "app:admin" "doctor" %}{% endblock %}
{% block doc_active %}active{% endblock %}

{% block tab_content %}
<div class="ui center aligned basic segment mt-5">
    <div  class="pt-5 w-75 mx-auto">
        <div class="d-flex flex-row align-items-center" style="background-color: white; border-radius: 7px;">
            <div>
                <img src="../../static/app/images/hero-illustration.png" style="height: 100px;" alt="Banner" class="img-fluid">
            </div>
            <div> Welcome, Add new doctors here.</div>
            <a class="ui teal button ms-3" href="{% url 'app:adminadddoc' %}">
                Add New Doctor
            </a>

        </div>
        
    </div>
    <div class="ui link cards w-75 mx-auto mb-5">
        {% for doc in doctors %}
            <div class="card mt-5 p-1 d-flex flex-row justify-content-between" style="background-color: white; border: 0; border-left: 1px solid #5174D5;">
                <div>
                    <div class="content left aligned ms-3">
                        <div class="header">{{ doc.full_name }}</div>
                        <div class="meta">
                            <a>@{{ doc.username }}</a>
                        </div>
                    </div>
                    <div class="content left aligned ms-3 p-1">
                        <div class="description">
                            {{ doc.admin_note }} <br/><br/>
                            Last Updated on : {{ doc.get_updated_on_date }}<br/>
                            Created on : {{ doc.get_created_on_date }}
                        </div>
                    </div>
                </div>
                <div class="extra content ms-3 p-1" >
                    <span class="right floated">
                        <a class="ui icon button p-2" href="{% url "app:admineditdoc" doc.username %}" style="color: black;">
                            edit
                        </a>
                        <a class="ui icon button p-2" href="{% url "app:admindeletedoc" doc.username %}" style="color: black;">
                            delete
                        </a>
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
    
</div>
{% endblock %}

doctris/app/templates/app/admin_page.html
{% extends 'app/base.html' %}
{% block title %}Doctris | Admin{% endblock %}

{% block nav%}
<style>
    .active{
        border-right: 3px solid #5174D5;
    }
</style>
<nav>
    <div class="mt-3 d-flex flex-row justify-content-between">
        <a class="" href="{% url "app:patienthome" %}"> 
            <img src="../../static/app/images/doctris-logo.png" class="img-fluid" width="180px">
        </a>
        <div class="right menu mt-4">
            {% if needs_login %}
                <a href="{% url "app:login" %}" class="ui item" id="sidebar-toggle"> Log In </a>
            {% endif %}
            {% if not needs_login %}
            <div class="d-flex">
                <div class="dropdown me-2">
                    <button class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: transparent; border: none;">
                         Admin
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="#dropdownMenuButton1">
                        <div class="right menu p-2">
                            {%block right_menu%}
                            {%endblock%}
                    </div>
                      </ul>
                </div>
                
                <div class="right menu">
                    {% if needs_login %}
                        <a href="{% url "app:login" %}" class="ui item" id="sidebar-toggle" style="color: black;"> Log In </a>
                    {% endif %}
                    {% if not needs_login %}
                        <a href="{% url "app:logout" %}" class="ui item" id="sidebar-toggle" style="color: black;"> Log Out </a>
                    {% endif %}
                </div>

            </div>
            
            {% endif %}
        </div>
    </div>
</nav>
{% endblock %}

{% block body %}
<section class="admin-page" style="min-height: 100%;">
    <div class="mt-3 d-flex flex-row">
            <div class="d-flex flex-column menu-bar" style="background-color: white;">
                <a class="mt-5 p-2 item {% block doc_active %}{% endblock %}" href="{% url "app:admin" "doctor" %}" style="color: #555555; text-decoration: none; font-weight: bold; ">
                    Doctor
                </a>
                <a class="mt-5 p-2 item {% block patient_active %}{% endblock %}" href="{% url "app:admin" "patient" %}" style="color: #555555; text-decoration: none; font-weight: bold; ">
                    Patient
                </a>
                <a class="mt-5 p-2 item {% block review_appointments_active %}{% endblock %}" href="{% url "app:admin" "adminreviewappoint" %}" style="color: #555555; text-decoration: none; font-weight: bold; ">
                    Review Appointments
                </a>
            </div>
   
        <div class="w-100" style="margin-right:-45px; position:relative; background-color: #EEF3FF; min-height: 1000px;">
            {% block tab_content %}
            {% endblock %}
        </div>
    </div>
</section>

{% endblock %}

doctris/app/templates/app/admin_pat_form.html
{% extends 'app/admin_page.html' %}

{% block home_click %}{% url "app:admin" "patient" %}{% endblock %}
{% block patient_active %}active{% endblock %}

{% block tab_content %}
{% if not success %}
    <div class="ui left aligned basic segment ms-5 mt-5" >
        <form class="ui form admin-pat-form" action="" method="POST" autocomplete="off">
            {% csrf_token %} 
            <h4 class="ui dividing header" >Register New Patient</h4>
            <div class="two fields mt-5">
                <div class="field required py-3">
                    <label>Username</label>
                    {% if as_edit %}
                        <input class="ms-3 p-2" type="text" name="username" value="{{obj.username}}" placeholder="Username" required autocomplete="off">
                    {% endif %}
                    {% if not as_edit %}
                        <input class="ms-3 p-2" type="text" name="username" placeholder="Username" required autocomplete="off">
                    {% endif %}
                </div>
                <div class="field required py-3">
                    {% if not as_edit %}
                        <label>Password</label>
                        <input class="ms-3 p-2" type="password" name="password"  pattern=".{6,}" title="Needs to be atleast 6 characters long." placeholder="Password" required autocomplete="off">
                    {% endif %}
                </div>
            </div>
            <div class="field required py-3">
                <div class="two fields">
                    <div class="field required">
                        <label>First Name</label>
                        {% if as_edit %}
                            <input class="ms-3 p-2" type="text" name="first_name" value="{{obj.first_name}}" required placeholder="First Name">
                        {% endif %}
                        {% if not as_edit %}
                            <input class="ms-3 p-2" type="text" name="first_name" required placeholder="First Name">
                        {% endif %}
                    </div>
                    <div class="field required py-3">
                        <label>Last Name</label>
                        {% if as_edit %}
                            <input class="ms-3 p-2" type="text" name="last_name" value="{{obj.last_name}}" required placeholder="Last Name">
                        {% endif %}
                        {% if not as_edit %}
                            <input class="ms-3 p-2" type="text" name="last_name" required placeholder="Last Name">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="field py-3">
                <label>Email</label>
                {% if as_edit %}
                    <input class="ms-3 p-2" type="email" name='email' value="{{obj.email}}" placeholder="Email">
                {% endif %}
                {% if not as_edit %}
                    <input class="ms-3 p-2" type="email" name='email' placeholder="Email">
                {% endif %}
            </div>
            <div class="field required py-3">
                <label>Phone</label>
                {% if as_edit %}
                    <input class="ms-3 p-2" type="text" name='phone' value="{{obj.phone}}" pattern=".{10,10}" required title="Needs to be 10 characters long." placeholder="Phone">
                {% endif %}
                {% if not as_edit %}
                    <input class="ms-3 p-2" type="text" name='phone'  pattern=".{10,10}" required title="Needs to be 10 characters long." placeholder="Phone">
                {% endif %}
            </div>
            <div class="field py-3">
                <label>Admin Notes</label>
                {% if as_edit %}
                    <textarea class="ms-3 p-2" rows="2" name="admin_note"> {{obj.admin_note}} </textarea>
                {% endif %}
                {% if not as_edit %}
                    <textarea class="ms-3 p-2" rows="2" name="admin_note">-</textarea>
                {% endif %}
            </div>
            <div class="ui error message"></div>
            {% if user_invalid %}
                <div class="ui negative message">
                    <p> The username is invalid. Please try another. </p>
                </div>
            {% endif %}
            <div class="ui horizontal divider" style="margin-top: 60px;">
                &nbsp;
            </div>
            <button class="ui teal button"type="submit" style="background-color: #5174D5; color: white; font-weight: bold; border: none;" >
                Submit
            </button>
        </form>
    </div>
{% endif %}

{% if success %}
    <div class="ui center aligned basic segment" style="margin-top: 60px;">
        <h1 class="ui icon header">
            <i class="check circle huge icon"></i>
            Success
        </h1>
        <div class="ui horizontal divider" style="margin-top: 60px;">
            &nbsp;
        </div>
        <div>
            <a class="ui teal  labeled icon button"type="submit" autofocus href="{% url "app:admin" "patient" %}" >
                View Patient
                <i class="eye icon" style="color:white" ></i>
            </a>
            {% if not as_edit %}
                <a class="ui teal labeled icon button"type="submit" href="{% url "app:adminaddpat" %}" >
                    New Patient
                    <i class="add icon" style="color:white"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endif %}
{% endblock %}

doctris/app/templates/app/admin_review_appointments_tab.html
{% extends 'app/admin_page.html' %}

{% block home_click %}{% url "app:admin" "adminreviewappoint" %}{% endblock %}
{% block review_appointments_active %}active{% endblock %}

{% block tab_content %}
    <div style="padding:7px;"></div>
    
    {% include './components/infoList/appointments.html'  with obj=review_appointments has_edit=False show_status=False as_admin=True as_custom=True title="Review Appointments" %}

{% endblock %}

doctris/app/templates/app/doctor_appointments_view.html
{% extends 'app/doctor_page.html' %}

{% block home_click %}{% url "app:doctor" %}{% endblock %}
{% block appointments_active %} active {% endblock %}
{% block right_menu%}
    <div class="ui simple dropdown item">
        General Actions
        <i class="dropdown icon"></i>
        <div class="menu">
            <a class="item"  href="{% url 'app:doctoreditinfo' %}" >Update Info</a>
            <a class="item"  href="{% url 'app:doctoreditcred' %}" >Change Password</a>
            <a class="item"  href="{% url "app:doctoractionavail" '-1' %}" >Add Avaliability</a>
            <a class="item" href="{% url "app:doctoractionspec" '-1' %}" >Add Specialties</a>
            <a class="item" href="{% url "app:doctoractionaff" '-1' %}" >Add Affiliations</a>
        </div>
    </div>
{% endblock %}

{% block tab_content %}
    <div style="padding:7px;"></div>
    {% include './components/appointments.html' %}
{% endblock %}

doctris/app/templates/app/doctor_page.html
{% extends 'app/base.html' %}
{% block title %}Doctris | Doctor{% endblock %}

{% block nav%}
<style>
    .active{
        border-right: 3px solid #5174D5;
    }
</style>
    <nav>
        <div class="mt-3 d-flex flex-row justify-content-between">
            <a class="" href="{% url "app:patienthome" %}"> 
                <img src="../../static/app/images/doctris-logo.png" class="img-fluid" width="180px">
            </a>
            <div class="right menu mt-4">
                {% if needs_login %}
                    <a href="{% url "app:login" %}" class="ui item" id="sidebar-toggle"> Log In </a>
                {% endif %}
                {% if not needs_login %}
                <div class="d-flex">
                    <div class="dropdown me-2">
                        <button class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: transparent; border: none;">
                             Dr. 
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="#dropdownMenuButton1">
                            <div class="right menu p-2">
                                {%block right_menu%}
                                {%endblock%}
                        </div>
                          </ul>
                    </div>
                    
                        <a href="{% url "app:logout" %}" class="ui item" id="sidebar-toggle" style="color: #5174D5; text-decoration: none; font-weight: bold;"> Log Out </a>

                </div>
                
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block body %}
<section class="admin-page" style="min-height: 100%;">
    <div class="mt-3 d-flex flex-row">
            <div class="d-flex flex-column menu-bar" style="background-color: white;">
                
                <a class="mt-5 p-2 item {% block appointments_active %}{% endblock %} "  href="{% url "app:doctorappointments" %}" style="color: #555555; text-decoration: none; font-weight: bold;  " >
                    Appointments
                </a>
                <a class="mt-5 p-2 item {% block profile_active %}{% endblock %}" href="{% url "app:doctor" %}" style="color: #555555; text-decoration: none; font-weight: bold;  " >
                    Profile
                </a>
                <a class="mt-5 p-2 item {% block notification_active %}{% endblock %}" href="{% url "app:doctornotif" %}" style="color: #555555; text-decoration: none; font-weight: bold;  " >
                    Notifications
                </a>
            </div>
   
        <div class="w-100" style="margin-right:-45px; position:relative; background-color: #EEF3FF; min-height: 1000px;">
            {% block tab_content %}
            {% endblock %}
        </div>
    </div>
</section>
{% endblock %}

doctris/app/templates/app/doctor_profile_edit_avail.html
{% extends 'app/doctor_page.html' %}

{% block home_click %}{% url "app:doctor" %}{% endblock %}
{% block profile_active %} active {% endblock %}

{% block tab_content %}
{% if not success %}
    <div class="ui left aligned ms-5" >
        <form class="ui form doc-cred-form" action="" method="POST" autocomplete="off">
            {% csrf_token %} 
            <div class="ui horizontal divider" style="margin-top: 28px" >Update Your Avaliability</div>
            <div style="padding:14px;">
                <div class="field required mt-5">
                    <label>Day</label>
                    {% if as_edit %}
                        <select class="ui dropdown" required name="day_in_week">
                            <option value="Sunday"
                                {% if obj.day_in_week == 'Sunday' %}
                                    selected
                                {% endif %}
                            >Sunday</option>
                            <option value="Monday"
                                {% if obj.day_in_week == 'Monday' %}
                                    selected
                                {% endif %}
                            >Monday</option>
                            <option value="Tuesday"
                                {% if obj.day_in_week == 'Tueday' %}
                                    selected
                                {% endif %}
                            >Tuesday</option>
                            <option value="Wedneday"
                                {% if obj.day_in_week == 'Wedneday' %}
                                    selected
                                {% endif %}
                            >Wedneday</option>
                            <option value="Thursday"
                                {% if obj.day_in_week == 'Thursday' %}
                                    selected
                                {% endif %}
                            >Thursday</option>
                            <option value="Friday"
                                {% if obj.day_in_week == 'Friday' %}
                                    selected
                                {% endif %}
                            >Friday</option>
                            <option value="Saturday"
                                {% if obj.day_in_week == 'Saturday' %}
                                    selected
                                {% endif %}
                            >Saturday</option>
                        </select>
                    {% endif %}
                    {% if not as_edit %}
                        <select class="ui dropdown" name="day_in_week">
                            <option value="Sunday"
                            >Sunday</option>
                            <option value="Monday"
                            >Monday</option>
                            <option value="Tuesday"
                            >Tuesday</option>
                            <option value="Wedneday"
                            >Wedneday</option>
                            <option value="Thursday"
                            >Thursday</option>
                            <option value="Friday"
                            >Friday</option>
                            <option value="Saturday"
                            >Saturday</option>
                        </select>
                    {% endif %}
                </div>
                <div class="field required mt-5">
                    <label>Start Time</label>
                    <input type="time" id="starting_time" value="{% if as_edit %}{{obj.starting_time}}{% endif %}" name="starting_time" min="00:00" max="24:00" required>
                </div>
                <div class="field required mt-5">
                    <label>End Time</label>
                    <input type="time" id="ending_time" name="ending_time"  value="{% if as_edit %}{{obj.ending_time}}{% endif %}" min="00:00" max="24:00" required>
                </div>
                <div class="ui error message"></div>
                {% if invalid_date %}
                    <div class="ui negative message">
                        <p> Ending time was before Start time. Please enter again. </p>
                    </div>
                {% endif %}
            </div>
            <div class="ui horizontal divider" >
                Proceed
            </div>
            <div style="padding: 14px">
                <div style="display:flex; justify-content:center; padding: 14px; ">
                    <button class="ui teal button"type="submit" style="margin-top: 5px;  background-color: #5174D5; color: white; font-weight: bolder;">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endif %}

{% if success %}
    <div class="ui center aligned basic segment" style="margin-top: 60px;">
        <h1 class="ui icon header">
            <i class="check circle huge icon"></i>
            Success
        </h1>
        <div class="ui horizontal divider" style="margin-top: 55px;">
            &nbsp;
        </div>
        <div>
            <a class="ui teal icon labeled button" autofocus type="submit" autofocus href="{% url "app:admin" "doctor" %}" >
                Profile
                <i class="eye icon" style="color:white"></i>
            </a>
            <a class="ui teal labeled icon button" type="submit" href="{% url "app:doctoractionavail" '-1' %}" >
                Add Another 
                <i class="add icon" style="color:white"></i>
            </a>
        </div>
    </div>
{% endif %}

{% endblock %}

doctris/app/templates/app/doctor_profile_edit_spec.html
{% extends 'app/doctor_page.html' %}

{% block home_click %}{% url "app:doctor" %}{% endblock %}
{% block profile_active %} active {% endblock %}

{% block tab_content %}
{% if not success %}
    <div class="ui left aligned ms-5" >
        <form class="ui form doc-cred-form" action="" method="POST" autocomplete="off">
            {% csrf_token %} 
            <div class="ui horizontal divider" style="margin-top: 28px" >Update Your Specialization</div>
            <div style="padding:14px;">
                <div class="field required mt-5">
                    <label>Specialization in</label>
                    {% if as_edit %}
                        <input type="text" name="specialization_in" value="{{obj.specialization_in}}" placeholder="Specialization In" required autocomplete="off">
                    {% endif %}
                    {% if not as_edit %}
                        <input type="text" name="specialization_in" placeholder="Specialization In" required autocomplete="off">
                    {% endif %}
                </div>
                <div class="field mt-5">
                    <label>Description</label>
                    {% if as_edit %}
                        <textarea rows="2" name="description"> {{obj.description}} </textarea>
                    {% endif %}
                    {% if not as_edit %}
                        <textarea rows="2" name="description">-</textarea>
                    {% endif %}
                </div>
                <div class="ui error message"></div>
            </div>
            <div style="padding: 14px">
                <div style="display:flex; justify-content:center;">
                    <button class="ui teal button"type="submit" style="margin-top: 5px; background-color: #5174D5; color: white; font-weight: bolder;">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endif %}

{% if success %}
    <div class="ui center aligned basic segment" style="margin-top: 60px;">
        <h1 class="ui icon header">
            <i class="check circle huge icon"></i>
            Success
        </h1>
        <div class="ui horizontal divider" style="margin-top: 55px;">
            &nbsp;
        </div>
        <div>
            <a class="ui teal icon labeled button" autofocus type="submit" autofocus href="{% url "app:admin" "doctor" %}" >
                Profile
                <i class="eye icon" style="color:white"></i>
            </a>
            <a class="ui teal labeled icon button" type="submit" href="{% url "app:doctoractionspec" '-1' %}" >
                Add Another 
                <i class="add icon" style="color:white"></i>
            </a>
        </div>
    </div>
{% endif %}

{% endblock %}

doctris/app/templates/app/doctor_profile_page.html
{% extends 'app/doctor_page.html' %}

{% block home_click %}{% url "app:doctor" %}{% endblock %}
{% block profile_active %} active {% endblock %}
{% block right_menu%}
    <div class="ui simple dropdown item">
        General Actions
        <i class="dropdown icon"></i>
        <div class="menu">
            <a class="item"  href="{% url 'app:doctoreditinfo' %}" >Update Info</a>
            <a class="item"  href="{% url 'app:doctoreditcred' %}" >Change Password</a>
            <a class="item"  href="{% url "app:doctoractionavail" '-1' %}" >Add Avaliability</a>
            <a class="item" href="{% url "app:doctoractionspec" '-1' %}" >Add Specialties</a>
            <a class="item" href="{% url "app:doctoractionaff" '-1' %}" >Add Affiliations</a>
        </div>
    </div>
{% endblock %}
{% block tab_content %}
    {% include './components/doctor_profile.html' with as_doctor=True %}   
{% endblock %}

doctris/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block title %}YouAppoint{% endblock %}

{% block nav%}
    <nav>
        <div class="ui secondary  menu">
            <a class="item logo large header" href="{% url "app:index" %}"> You <span class="ui teal">Appoint</span> </a>
            <div class="right menu">
                <a href="{% url "app:login" %}" class="ui item" id="sidebar-toggle"> Log In </a>
                <a href="{% url "app:signup" %}" class="ui item" id="sidebar-toggle"> Sign Up </a>
            </div>
        </div>
    </nav>
{% endblock %}

{% block body %}
<section class="home-page">
    Home Page!
</section>
{% endblock %}

doctris/app/templates/app/patient_doctor_appointment.html
{% extends 'app/patient_page.html' %}

{% block home_click %}{% url "app:patient" %}{% endblock %}
{% block appointments_active %} active {% endblock %}

{% block tab_content %}
    {% include './components/appointment_form.html' %}
{% endblock %}

doctris/app/templates/app/patient_doctor_view.html
{% extends 'app/patient_page.html' %}

{% block home_click %}{% url "app:patient" %}{% endblock %}
{% block profile_active %} active {% endblock %}

{% block tab_content %}
    {% include './components/doctor_profile.html' %}
    <div class="ui center aligned basic segment">
        <a class="ui teal labeled icon button" href="{% url 'app:patientdocappoint' doctor.username '-1'  %}">
            Set Appointment
            <i class="add icon" style="color:white"></i>
        </a>
    </div>
{% endblock %}

doctris/app/templates/app/patient_notif_page.html
{% extends 'app/patient_page.html' %}

{% block home_click %}{% url "app:patientnotif" %}{% endblock %}
{% block notification_active %} active {% endblock %}
{% block right_menu%}
    <div class="ui simple dropdown item">
        General Actions
        <i class="dropdown icon"></i>
        <div class="menu">
            <a class="item"  href="{% url 'app:patienteditinfo' %}" >Update Info</a>
            <a class="item"  href="{% url 'app:patienteditcred' %}" >Change Password</a>
        </div>
    </div>
{% endblock %}
{% block tab_content %}
    {% include './components/notifications.html' %}
{% endblock %}